# Dados de conexão do PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/concessionaria

# Utilizando variáveis de ambiente para user e senha
# Configure no seu windows/linux ou no próprio intellij
# no IntelliJ clique na seta ao lado do botão de executar
# vá em edit configurations
# modify options e environment variables
# no campo que aparecer clique no documento para editar as variáveis
# bote USER_BD e o usuário do seu banco de dados PostgreSQL
# bote SENHA_BD e a senha do seu banco
spring.datasource.username=${USER_BD}
spring.datasource.password=${SENHA_BD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect