# Linkzinho pro jotadê bê cê
spring.datasource.url=jdbc:postgresql://localhost:5432/concessionaria

# Pra facilitar e manter o user e o password do banco privado ao commitar no GitHub
# to usando variável de ambiente como o meu grupo fez no POO
# mas o IntelliJ tem variaveis de ambiente embutidas

# configura assim:
# vai na setinha do do lado do botão de rodar lá em cima no Application
# vai em Edit Configuration
# vai em Modify Options
# vai em Environment Variables
# ao clicar vai abrir um campo onde vc coloca:
# USER_BD=seu_user;SENHA_BD=sua senha
# ou clica na lateral do campo, num ícone de documento
# e coloca USER_BD no name, e seu user do postgre no value
# e o mesmo pra senha

spring.datasource.username=${USER_BD}
spring.datasource.password=${SENHA_BD}

spring.datasource.driver-class-name=org.postgresql.Driver

# Configs pro Hibernate/JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Linhazinha pras URL ficarem de acordo com o Swagger
server.servlet.context-path=/api/v1